// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb6JRQg1mv6yyHiiGRK9sjTOUNG1X37k8',
    appId: '1:806184078855:web:4e567ba7c92a2ac813a4a2',
    messagingSenderId: '806184078855',
    projectId: 'flutterdoctorapp-f1e1f',
    authDomain: 'flutterdoctorapp-f1e1f.firebaseapp.com',
    storageBucket: 'flutterdoctorapp-f1e1f.firebasestorage.app',
    measurementId: 'G-LELS3DRPED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOcwQLBHARkdBBxZOzw-wDSDDLW1X2-PU',
    appId: '1:806184078855:android:ab524518330a1f8513a4a2',
    messagingSenderId: '806184078855',
    projectId: 'flutterdoctorapp-f1e1f',
    storageBucket: 'flutterdoctorapp-f1e1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNaby5ifgRCxHsWy-hxtX-ixu9vn7s60k',
    appId: '1:806184078855:ios:86c43d6d7a68800c13a4a2',
    messagingSenderId: '806184078855',
    projectId: 'flutterdoctorapp-f1e1f',
    storageBucket: 'flutterdoctorapp-f1e1f.firebasestorage.app',
    androidClientId: '806184078855-72cftpdl8kovagrgto760a973k8dum1c.apps.googleusercontent.com',
    iosClientId: '806184078855-4slt18ro7lrosgeiavicpvl79enslhd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNaby5ifgRCxHsWy-hxtX-ixu9vn7s60k',
    appId: '1:806184078855:ios:86c43d6d7a68800c13a4a2',
    messagingSenderId: '806184078855',
    projectId: 'flutterdoctorapp-f1e1f',
    storageBucket: 'flutterdoctorapp-f1e1f.firebasestorage.app',
    androidClientId: '806184078855-72cftpdl8kovagrgto760a973k8dum1c.apps.googleusercontent.com',
    iosClientId: '806184078855-4slt18ro7lrosgeiavicpvl79enslhd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmwvJCsgB0s1NOE5xiL3hlw-po9um9vFs',
    appId: '1:806184078855:web:0f733afc30b681bd13a4a2',
    messagingSenderId: '806184078855',
    projectId: 'flutterdoctorapp-f1e1f',
    authDomain: 'flutterdoctorapp-f1e1f.firebaseapp.com',
    storageBucket: 'flutterdoctorapp-f1e1f.firebasestorage.app',
    measurementId: 'G-F78T1R2T7C',
  );

}